// <auto-generated />
using System;
using Authentication.POC.API.JWT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authentication.POC.API.JWT.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220622072814_InitialPOCUserData")]
    partial class InitialPOCUserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Authentication.POC.API.JWT.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34c96152-329d-4463-81c2-481ce4e79e85"),
                            CreatedAt = new DateTime(2022, 6, 22, 7, 28, 14, 706, DateTimeKind.Utc).AddTicks(5440),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("6721a7a3-1855-40d0-b5a2-23205acf36f2"),
                            CreatedAt = new DateTime(2022, 6, 22, 7, 28, 14, 706, DateTimeKind.Utc).AddTicks(5444),
                            Name = "Editor"
                        },
                        new
                        {
                            Id = new Guid("dd5ac686-f64a-4dd4-bd19-9427d7c34eea"),
                            CreatedAt = new DateTime(2022, 6, 22, 7, 28, 14, 706, DateTimeKind.Utc).AddTicks(5445),
                            Name = "Writer"
                        });
                });

            modelBuilder.Entity("Authentication.POC.API.JWT.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("061b4cfa-e1ba-4983-b395-d93e651e5559"),
                            CreatedAt = new DateTime(2022, 6, 22, 7, 28, 14, 706, DateTimeKind.Utc).AddTicks(5602),
                            Email = "dev@philippines.com",
                            Enabled = true,
                            Name = "Lester Feria",
                            Password = "123456",
                            RoleId = new Guid("34c96152-329d-4463-81c2-481ce4e79e85")
                        });
                });

            modelBuilder.Entity("Authentication.POC.API.JWT.Data.Entities.User", b =>
                {
                    b.HasOne("Authentication.POC.API.JWT.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
